[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
script = 'scripts/foundry'
test = 'test/foundry'

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config